# Generated by Django 5.2.8 on 2025-12-12 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_hostel_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('apply_state', models.CharField(choices=[('待审核', '待审核'), ('通过', '通过'), ('拒绝', '拒绝')], default='pending', max_length=20, verbose_name='申请状态')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_apply', to='users.hostel', verbose_name='申请宿舍')),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_apply', to=settings.AUTH_USER_MODEL, verbose_name='申请老师')),
            ],
            options={
                'verbose_name': '宿舍申请记录',
                'verbose_name_plural': '宿舍申请记录',
            },
        ),
    ]
