"""
Django settings for ManagerApi project.

Generated by 'django-admins startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))                   # 添加apps目录(系统路径)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n8t17=+(o4t2mut8_mh#qd9c4bynj=yh*vmo1na6pvz*f%9fj_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


# Application definition

# app
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'django_redis',
    'users',
    'teacher',
]
# 添加自定义认证后端 (实现多表登录的关键)
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# rest_framewor配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [                              # 添加jwt认证
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # 配置分页类
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,                                                 # 返回的数据
    # 添加过滤器
    'DEFAULT_FILTER_BACKENDS': [
            'django_filters.rest_framework.DjangoFilterBackend',
        ]
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),              # 访问token有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),             # 刷新token有效期
    'ROTATE_REFRESH_TOKENS': True,                           # 刷新token有效期
    'BLACKLIST_AFTER_ROTATION': True,                        # 把旧令牌加入到黑名单
    'SIGNING_KEY':SECRET_KEY,                                # 密钥
    # 配置令牌的认证头部类型
    'AUTH_HEADER_TYPES': ('Hander',),                        # 客户端发送的 HTTP 头部中，指定认证令牌的类型为 "Hander"。
    'ALGORITHM': 'HS256',                                    # 加密算法
}

# 中间件
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ManagerApi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 数据库配置
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # 使用MySQL引擎
        'NAME': 'student_manager',             # 要连接的数据库名
        'USER': 'root',                        # 数据库用户名
        'PASSWORD': 'root',                    # 数据库密码
        'HOST': '127.0.0.1',                   # 数据库主机地址，本地默认127.0.0.1
        'PORT': '3306',                        # MySQL端口，默认3306
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',  # 使用SQLite引擎
#         'NAME': BASE_DIR / 'db.sqlite3',         # 数据库文件路径
#     }
# }

# redis数据库配置
CACHES = {
    # 默认缓存数据
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/13',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    },
}

# 日志配置
# 四个关键配置：formatters（格式化器）、handlers（处理器）、loggers（记录器）
LOGGING = {
    'version': 1,                                                              # 日志版本
    'disable_existing_loggers': False,
    'formatters': {
        # verbose格式化器
        'verbose': {
            # levelname 日志级别 asctime 时间 module模块 lineno行号 message日志信息
            'format': '%(levelname)s %(asctime)s %(module)s %(lineno)d %(message)s'
        },
    },
    # 定义日志输出位置
    'handlers': {
        # 日志文件保存
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',                   # RotatingFileHandler文件处理器
            'filename': os.path.join(BASE_DIR, 'logs/sm.log'),                 # 输出文件路径
            'maxBytes': 300 * 1024 * 1024,                                     # 单个文件300MB
            'backupCount': 10,                                                 # 创建的最多文件
            'formatter': 'verbose'                                             # 使用verbose格式化器
        },
        # 日志控制台输出
        'console': {
            'level': 'INFO',
            # 流式输出
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        }
    },
    # 应用程序中直接用来记入日志的接口
    'loggers': {
        'django': {
            'handlers': ['file','console'],                                    # 指定输出方式
            'propagate': True,
        },
    }
}

WSGI_APPLICATION = 'ManagerApi.wsgi.application'

# 用户模型
AUTH_USER_MODEL = 'users.User'

# 密码验证
AUTH_PASSWORD_VALIDATORS = []         # 测试
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]

# 语言和时区
LANGUAGE_CODE = 'zh-hans'
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

# 静态文件和上传文件配置
STATIC_URL = 'static/'                                               # 静态文件路由
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]              # 静态文件目录
MEDIA_URL = '/media/'                                                # 上传文件路由
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')                       # 上传文件目录

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
