# Generated by Django 5.2.8 on 2025-11-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_hostel_gender_user_gender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostel',
            unique_together=set(),
        ),
    ]
