# Generated by Django 5.2.8 on 2025-11-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(choices=[('0', '学生管理'), ('1', '教师管理'), ('2', '宿舍出行管理'), ('3', '楼层信息管理')], max_length=100, verbose_name='管理员选项')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
            ],
            options={
                'verbose_name': '管理员选项',
                'verbose_name_plural': '管理员选项',
                'db_table': 'admin_options',
            },
        ),
    ]
