# Generated by Django 5.2.8 on 2025-11-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_adminoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminoptions',
            name='options',
            field=models.CharField(max_length=100, unique=True, verbose_name='管理员选项'),
        ),
    ]
