# Generated by Django 5.2.8 on 2025-12-06 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostels_manager', to=settings.AUTH_USER_MODEL, verbose_name='管理员老师'),
        ),
    ]
